c.completion.shrink = True
c.completion.web_history_max_items = 10
c.downloads.location.directory = "/home/asarkar/incoming"
c.editor.command = ["emacsclient", "{}"]
c.hints.scatter = False
c.hints.uppercase = True
c.tabs.new_position.related = "last"
c.tabs.show = "never"
c.url.default_page = "about:blank"
c.url.searchengines = {'DEFAULT': 'https://www.google.com/search?q={}', 'maps': 'https://maps.google.com/?q={}'}
c.url.start_pages = ['qute://settings']

# solarized colors

base03 = "#002b36"
base02 = "#073642"
base01 = "#586e75"
base00 = "#657b83"
base0 = "#839496"
base1 = "#93a1a1"
base2 = "#eee8d5"
base3 = "#fdf6e3"
yellow = "#b58900"
orange = "#cb4b16"
red = "#dc322f"
magenta = "#d33682"
violet = "#6c71c4"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"

c.colors.completion.category.bg = base3
c.colors.completion.category.border.bottom = base3
c.colors.completion.category.border.top = base3
c.colors.completion.category.fg = base00
c.colors.completion.even.bg = base3
c.colors.completion.fg = base00
c.colors.completion.item.selected.bg = base2
c.colors.completion.item.selected.border.bottom = base2
c.colors.completion.item.selected.border.top = base2
c.colors.completion.item.selected.fg = base00
c.colors.completion.match.fg = red
c.colors.completion.odd.bg = base3
c.colors.completion.scrollbar.bg = base3
c.colors.completion.scrollbar.fg = base00
c.colors.downloads.bar.bg = base3
c.colors.downloads.error.bg = base3
c.colors.downloads.error.fg = red
c.colors.downloads.start.bg = base3
c.colors.downloads.start.fg = base1
c.colors.downloads.stop.bg = base3
c.colors.downloads.stop.fg = base00
c.colors.hints.bg = base3
c.colors.hints.fg = base00
c.colors.hints.match.fg = red
c.colors.keyhint.bg = base3
c.colors.keyhint.fg = base00
c.colors.keyhint.suffix.fg = cyan
c.colors.messages.error.bg = base3
c.colors.messages.error.border = base3
c.colors.messages.error.fg = red
c.colors.messages.info.bg = base3
c.colors.messages.info.border = base3
c.colors.messages.info.fg = base1
c.colors.messages.warning.bg = base3
c.colors.messages.warning.border = base3
c.colors.messages.warning.fg = orange
c.colors.statusbar.caret.bg = base3
c.colors.statusbar.caret.fg = violet
c.colors.statusbar.caret.selection.bg = base3
c.colors.statusbar.caret.selection.fg = violet
c.colors.statusbar.command.bg = base3
c.colors.statusbar.command.fg = base00
c.colors.statusbar.command.private.bg = base03
c.colors.statusbar.command.private.fg = base0
c.colors.statusbar.insert.bg = base3
c.colors.statusbar.insert.fg = cyan
c.colors.statusbar.normal.bg = base3
c.colors.statusbar.normal.fg = base00
c.colors.statusbar.private.bg = base03
c.colors.statusbar.private.fg = base0
c.colors.statusbar.progress.bg = base3
c.colors.statusbar.url.error.fg = red
c.colors.statusbar.url.fg = base00
c.colors.statusbar.url.success.http.fg = red
c.colors.statusbar.url.success.https.fg = base00
c.colors.statusbar.url.warn.fg = orange

monospace = "10pt monospace"

c.fonts.completion.category = "bold" + monospace
c.fonts.completion.entry = monospace
c.fonts.downloads = monospace
c.fonts.hints = "bold 10pt monospace"
c.fonts.keyhint = monospace
c.fonts.messages.error = monospace
c.fonts.messages.info = monospace
c.fonts.messages.warning = monospace
c.fonts.monospace = "Consolas"
c.fonts.prompts = "10pt sans-serif"
c.fonts.statusbar = monospace
c.fonts.web.family.fixed = "Consolas"
c.fonts.web.family.sans_serif = "Fontin Sans"
c.fonts.web.family.serif = "Fontin"
c.fonts.web.family.standard = "Fontin"
